name: shopping_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.9.1
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  flutter_lints: ^1.0.4
  share_plus: ^7.1.0
  flutter_email_sender: ^6.0.1
  mailer: ^6.0.1
  barcode_scan2: ^4.2.0
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.7.0
  image_picker: ^1.0.4

  # Visual Elements 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  animate_do: ^2.1.0

  # State Management
  provider: ^6.0.2

  # Api Connection
  dio: ^4.0.4
  connectivity_plus: ^2.2.0

  #qrCode
  qr_flutter: ^4.1.0

  # Json Operations
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

  # Log
  logger: ^1.1.0
  firebase_database: ^10.2.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  device_preview: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Chicken_01/Chicken_01.gltf
    - assets/images/Table_wooden.obj
    - assets/images/icons/facebook.png
    - assets/images/icons/google.png
    - assets/images/icons/linkedin.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf    